#!/bin/bash

set -eu

DEBUG=0

DEVICE_BASE=/sys/devices/platform/pwm-fan/hwmon/hwmon3

# declare -a CpuTemps=(75000 65000 55000 50000 45000 40000 0)
# declare -a PwmDec=(255 150 90 80 70 60 0)
declare -a CpuTemps=(70000 55000 50000 45000 40000 35000 0)
declare -a PwmDec=(255 100 80 70 60 55 0)

while true; do
        temp=$(< /sys/class/thermal/thermal_zone0/temp)
        for i in 0 1 2 3 4 5 6; do
                if [ "$temp" -gt "${CpuTemps[$i]}" ]; then
                    duty=$(( 0 + PwmDec[$i] ))
                        echo "$duty" > "$DEVICE_BASE/pwm1"
                        [ $DEBUG -gt 0 ] && echo "temp: $temp, target: ${CpuTemps[$i]}, duty: $duty"
                        break
                fi
        done
        sleep 2
done
